version: 2
jobs:
  test:
    docker:
      - image: almalinux:9 # We support EL8, but dpkg-dev is not installable in EPEL 8
    steps:
      - checkout
      - run: 'dnf --assumeyes install perl-App-cpanminus gettext gcc epel-release'
      - run: 'dnf --assumeyes install dpkg-dev fakeroot'
      - run: 'perl -V'
      - run: 'cpanm --notest --installdeps .'
      - run: './configure'
      - run: 'make'
      - run: 'make check'

workflows:
  version: 2
  test:
    jobs:
      - test
